Vagrant.configure("2") do |config|

    config.vm.define "master" do |master|
        master.vm.box = "centos/7"
        master.vm.hostname = "ansible"
        master.vm.network "private_network", ip: "192.168.33.200"
        master.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "CentOS-Master"
            vb.memory = "1024"
            vb.cpus = "1"
        end
    end
 
    config.vm.define "client1" do |client1|
        client1.vm.box = "centos/7"
        client1.vm.hostname = "centos"
        client1.vm.network "private_network", ip: "192.168.33.201"
        client1.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "CentOS-Client"
            vb.memory = "1024"
            vb.cpus = "1"
        end
    end
 
    config.vm.define "client2" do |client2|
        client2.vm.box = "debian/stretch64"
        client2.vm.hostname = "debian"
        client2.vm.network "private_network", ip: "192.168.33.202"
        client2.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "Debian-Client"
            vb.memory = "1024"
            vb.cpus = "1"
        end
    end
  end 