Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.define  "Fantasma"
    config.vm.hostname = "LabUm"
    config.vm.network "private_network", ip: "10.2.3.4", bridge: "wlp3s0"
    end
    
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.define  "Pumba"
    config.vm.hostname = "LabDois"
    config.vm.network "private_network",ip: "10.2.3.5", bridge: "wlp3s0"
    end
end


+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.define  "Fantasma"
    config.vm.hostname = "LabUm"
    config.vm.network "public_network", bridge: "wlp3s0"
    end
